-- Gym Member Management System : database schema (PostgreSQL)
-- ตารางและคอลัมน์ตรงกับ Entity ใน domain/entity ทุกตัว
-- รันซ้ำได้ (IF NOT EXISTS)

CREATE TABLE IF NOT EXISTS trainer (
    trainer_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    phone       VARCHAR(255),
    specialty   VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS member (
    member_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(255) NOT NULL,
    email       VARCHAR(255),
    password    VARCHAR(255) NOT NULL,
    phone       VARCHAR(255),
    trainer_id  BIGINT REFERENCES trainer (trainer_id)
);

CREATE TABLE IF NOT EXISTS member_info (
    info_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id          BIGINT NOT NULL UNIQUE REFERENCES member (member_id),
    full_name          VARCHAR(255) NOT NULL,
    gender             VARCHAR(255),
    date_of_birth      DATE,
    emergency_contact  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS membership_plan (
    plan_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name      VARCHAR(255) NOT NULL,
    price          NUMERIC(38, 2) NOT NULL,
    duration_days  INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS membership (
    membership_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      BIGINT NOT NULL REFERENCES member (member_id),
    plan_id        BIGINT NOT NULL REFERENCES membership_plan (plan_id),
    start_date     DATE NOT NULL,
    end_date       DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS training_session (
    session_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id    BIGINT NOT NULL REFERENCES trainer (trainer_id),
    member_id     BIGINT NOT NULL REFERENCES member (member_id),
    session_date  DATE NOT NULL,
    session_time  TIME NOT NULL,
    status        VARCHAR(255) NOT NULL
);

-- Index: PostgreSQL ไม่สร้าง index ให้ foreign key อัตโนมัติ
-- (member_info.member_id มี index อยู่แล้วจาก UNIQUE)
CREATE INDEX IF NOT EXISTS idx_member_trainer_id            ON member (trainer_id);
CREATE INDEX IF NOT EXISTS idx_member_username              ON member (username);
CREATE INDEX IF NOT EXISTS idx_membership_member_id         ON membership (member_id);
CREATE INDEX IF NOT EXISTS idx_membership_plan_id           ON membership (plan_id);
CREATE INDEX IF NOT EXISTS idx_membership_end_date          ON membership (end_date);
CREATE INDEX IF NOT EXISTS idx_training_session_trainer_id  ON training_session (trainer_id);
CREATE INDEX IF NOT EXISTS idx_training_session_member_id   ON training_session (member_id);
CREATE INDEX IF NOT EXISTS idx_training_session_date        ON training_session (session_date);