spring.application.name=membership
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_db
spring.datasource.username=postgres
spring.datasource.password=Auto7532
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true